import Head from 'next/head'
import Avatar from "../components/Avatar";
import {BeakerIcon, ViewGridIcon} from '@heroicons/react/solid'
import Image from "next/image";
import {SearchIcon} from "@heroicons/react/outline";
import { MicrophoneIcon } from "@heroicons/react/solid";
import Footer from "../components/Footer";
import {useRef} from "react";
import {useRouter} from "next/router";


export default function Home() {

    const searchInputRef = useRef(null);
    const router = useRouter();

    const search = e => {
        e.preventDefault();
        const term = searchInputRef.current.value;

        if(!term) {
            return;
        }

        router.push(`/search?term=${term}`);




    }
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://pngimg.com/uploads/google/google_PNG19635.png" />
      </Head>

    {/*    Header   */}
        <header className="flex w-full p-5 justify-between text-sm text-gray-700">
            <div className="flex space-x-4 items-center">
            {/*    left*/}
                <p className="link">About</p>
                <p  className="link">Store</p>
            </div>

            <div className="flex space-x-4 items-center">
            {/*    right*/}
                <p className="link">Gmail</p>
                <p className="link">Images</p>


                <ViewGridIcon className=" cursor-pointer h-10 w-10 p-2 rounded-full hover:bg-gray-100"/>

            {/*    icon */}

                <Avatar className="h-10" />

            {/*    avatar*/}


            </div>
        </header>
    {/*    Body */}

        <form action="" className="flex flex-col items-center mt-44 flex-grow w-4/5">
            <Image
                src="https://www.google.lt/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png" height={100} width={300}

            />

            <div
                className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full
          border border-gray-200  px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl"
            >
                <SearchIcon className="h-5 mr-3 text-gray-500" />
                <input
                    ref={searchInputRef}
                    type="text"
                    className="flex-grow focus:outline-none "
                />
                <MicrophoneIcon className="h-5" />
            </div>

            <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm: space-x-4">
                <button onClick={search} className="btn">Google Search</button>
                <button onClick={search} className="btn">I'm feeling Lucky</button>
            </div>
        </form>

        <Footer />
    {/*    Footer   */}

    </div>
  )
}
