import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/*    Header   */}
        <header className="flex w-full p-5 justify-between text-sm text-gray-700">
            <div className="flex space-x-4 items-center">
            {/*    left*/}
                <p>About</p>
                <p>Store</p>
            </div>

            <div className="flex space-x-4 items-center">
            {/*    right*/}
                <p>Gmail</p>
                <p>Images</p>


            {/*    icon */}

            {/*    avatar*/}
            </div>
        </header>
    {/*    Body */}
    {/*    Footer   */}

    </div>
  )
}
